export interface Order{
  name: string,
  szamOrsz: string,
  szamIr: string,
  szamVar: string,
  szamUtca: string,
  szalOrsz: string,
  szalIr: string,
  szalVar: string,
  szalUtca: string,
  kupon: string,
  cardNum: string,
  cardDate: string,
  cardCvc: string,
}
